### ISSUE TITLE
What does this line suppose to do ?

### ISSUE THREAD

**Issue by ZaidRehman** [wilsonwu/vuetify-audio#2]
https://github.com/wilsonwu/vuetify-audio/blob/990d1555593d6de230c3e69dbdad4a5c7326fb01/src/vuetifyaudio.vue#L92

Unable to understand what is the use of this line.

**Your work is great and works like charm**

**Comment by aliddy23** [comment]
When muting is toggled, it will set volumeValue to 0. If it is not muted, it will set volumeValue to 75.
