### ISSUE TITLE
Doesn't play on ios phones. 

### ISSUE THREAD

**Issue by husayt** [wilsonwu/vuetify-audio#4]
Had to show audio player by adding controls attribute for this to work on ios.

**Comment by wilsonwu** [comment]
Thanks submit this issue, and I tested in my iPhone XR, it works fine from the demo site:
![image](https://user-images.githubusercontent.com/1269496/71721289-7bae1b00-2e5f-11ea-8f54-791363410205.png)

**Comment by wilsonwu** [comment]
@husayt If you don't have further problem, I will close this issue in 3 days (till 2020/3/2), thanks for your support.

**Comment by talshadar** [comment]
Hi.  Sorry to comment on an old post- but is it possible to see the code?  I'm not completely sure what is meant by adding control attributes?
