### ISSUE TITLE
Not support some non-standard wav file.

### ISSUE THREAD

**Issue by angryreid** [wilsonwu/vuetify-audio#7]
Have you ever met audio tag can't play some non-standard wav files?

**Comment by wilsonwu** [comment]
Could you send me some non-standard wav file sample? That I can try to find some solutions.

**Comment by angryreid** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wilson Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 晚上7:33
收件人:&nbsp;"wilsonwu/vuetify-audio"<vuetify-audio@noreply.github.com&gt;;
抄送:&nbsp;"爱笑的Emma呀"<dxiang1391458323@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wilsonwu/vuetify-audio] Not support some non-standard wav file. (#7)




Could you send me some non-standard wav file sample? That I can try to find some solutions.
