### ISSUE TITLE
pause when click stop button? 

### ISSUE THREAD

**Issue by ghost** [wilsonwu/vuetify-audio#8]
I felt unnatural behavior. 

1. push play button, then play audio
2. when playing audio, push stop button
3. then keep pause button, not play button. 

i expected that pause button should go back to play button when click the stop button?
Am I wrong somehow?

**Comment by wilsonwu** [comment]
Thanks for report this bug, I will fix it asap.

**Comment by wilsonwu** [comment]
@toshimi fixed, please use the 0.3.2 version, thank you again.
