### ISSUE TITLE
Removing V-card tag

### ISSUE THREAD

**Issue by Adarshreddyash** [wilsonwu/vuetify-audio#9]
Existing v-card tag will restrict users to use v-card. Few may have requirements like adding audio title , Image. My bad ! If there is any way to add them within the existing card ??

Thanks,

**Comment by wilsonwu** [comment]
Thanks for your suggestion, I will add a prop that can make the v-card flat, after that you can combine your image and title with this control in you page.

**Comment by wilsonwu** [comment]
@Adarshreddyash all done, please use the latest version 0.3.3 for a try, welcome for any suggestions :)
